dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: Extracted key value
    displayType: state
    state:
      label: '{{keyvalue.value}}'
automation:
  conditions:
    - label: Extracted key value
      displayType: textField
      textField:
        value: keyvalue.value
        valueType: string
  actions: []
id: partyvoice23922.keyvalue
version: 1
